//Категории разных понятий

const foodNames = [
	"asparagus",
	"apples",
	"avacado",
	"alfalfa",
	"acorn",
	"almond",
	"arugala",
	"artichoke",
	"applesauce",
	"noodles",
	"antelope",
	"tuna",
	"albacore",
	"apple",
	"avocado",
	"roll",
	"bruscetta",
	"bacon",
	"beans",
	"bagels",
	"bean",
	"bbq",
	"bison",
	"barley",
	"beer",
	"bisque",
	"bluefish",
	"bread",
	"broccoli",
	"buritto",
	"babaganoosh",
	"cabbage",
	"cake",
	"carrots",
	"celery",
	"cheese",
	"chicken",
	"catfish",
	"chips",
	"chocolate",
	"chowder",
	"clams",
	"coffee",
	"cookies",
	"corn",
	"cupcakes",
	'crab',
	'curry', 
	'cereal', 
	'chimichanga', 
	'dips', 
	'duck', 
	'dumplings', 
	'donuts', 
	'donut', 
	'eggs', 
	'egg', 
	'enchilada', 
	'eggrolls', 
	'muffins', 
	'muffin', 
	'edimame', 
	'sushi', 
	'fajita', 
	'falafel', 
	'fish', 
	'franks', 
	'fondu', 
	'toast', 
	'dip', 
	'garlic', 
	'ginger', 
	'gnocchi', 
	'goose', 
	'granola', 
	'grapes', 
	'guancamole', 
	'gumbo', 
	'grits', 
	'crackers', 
	'cracker', 
	'ham', 
	'halibut', 
	'hamburger', 
	'cheeseburgers', 
	'cheeseburger', 
	'honey', 
	'hashbrown', 
	'hummus', 
	'cream', 
	'stew', 
	'food', 
	'bread', 
	'jambalaya', 
	'jelly', 
	'jam', 
	'jerky', 
	'jalapeño', 
	'kale', 
	'kabobs', 
	'ketchup', 
	'kiwi', 
	'kidney', 
	'kingfish', 
	'lobster', 
	'lamb', 
	'linguine', 
	'lasagna', 
	'meatballs', 
	'moose', 
	'milk', 
	'milkshake', 
	'noodles', 
	'ostrich', 
	'pizza', 
	'pepperoni', 
	'porter', 
	'pancakes', 
	'quesadilla', 
	'quiche', 
	'reuben', 
	'spinach', 
	'spaghetti', 
	'tots', 
	'toast', 
	'venison', 
	'waffles', 
	'waffle', 
	'wine', 
	'walnuts', 
	'walnut', 
	'yogurt', 
	'ziti', 
	'zucchini', 
	'zander', 
	'zapiekanka', 
	'zarzuela', 
	'zeppole', 
	'zerde', 
	'ziti', 
	'zongzi', 
	'zoni', 
	'zucchini', 
	'zuccotto', 
	'zander',
	"cake",
	"zucchini",
	"zigni",
	"ziti",
	"zimtsterne",
	"zaboca",
	"zhejiang",
	"zampone",
]
export{foodNames}
//еда
const natureWords = [
	"tree",
	"sun",
	"river",
	"mountain",
	"ocean",
	"clouds",
	"rain",
	"wind",
	"flower",
	"forest",
	"field",
	"lake",
	"sky",
	"grass",
	"rock",
	"sand",
	"dune",
	"valley",
	"canyon",
	"waterfall",
	"meadow",
	"desert",
	"island",
	"volcano",
	"tundra",
	"bamboo",
	"delta",
	"glacier",
	"lagoon",
	"reef",
	"cave",
	"plateau",
	"marsh",
	"pond",
	"summit",
	"rift",
	"fjord",
	"delta",
	"gulf",
	"savanna",
	"estuary",
	"cliff",
	"ridge",
	"stream",
	"hill",
	"bay",
	"quarry",
	"heath",
	"swamp",
	"ravine",
	"oasis",
	"crater",
	"basin",
	"promontory",
	"dell",
	"crag",
	"grove",
	"floodplain",
	"foothill",
	"quagmire",
	"arctic",
	"bush",
	"gorge",
	"fen",
	"knoll",
	"pinnacle",
	"escarpment",
	"alluvial",
	"estuary",
	"upland",
	"taiga",
	"saltmarsh",
	"crag",
	"tableland",
	"trellick",
	"beach",
	"wetland",
	"canyon",
	"wadi",
	"rainforest",
	"mesa",
	"prairie",
	"tropics",
	"arroyo",
	"bight",
	"trial",
	"cape",
	"isthmus",
	"moor",
	"foreland",
	"corrie",
	"polynya",
	"pocosin",
	"lava",
	"pebble",
	"gully"
]
export{natureWords}
//природа
const waterWords = [
	"ocean",
	"waves",
	"current",
	"tide",
	"surf",
	"beach",
	"seashore",
	"seagull",
	"whale",
	"dolphin",
	"ship",
	"sailboat",
	"sail",
	"anchor",
	"lighthouse",
	"tropical",
	"shell",
	"coral",
	"reef",
	"coastline",
	"seafloor",
	"shoreline",
	"beacon",
	"marina",
	"buoy",
	"jetty",
	"harbor",
	"pier",
	"wave",
	"tsunami",
	"oceanography",
	"buccaneer",
	"shipwreck",
	"captain",
	"crew",
	"compass",
	"navigation",
	"sailing",
	"fisherman",
	"sinker",
	"net",
	"lobster",
	"channel",
	"freshwater",
	"seaweed",
	"foghorn",
	"wharf",
	"surfing",
	"beachcomber",
	"kayak",
	"paddle",
	"snorkeling",
	"underwater",
	"dive",
	"submarine",
	"cruise",
	"sandy",
	"swimming",
	"lifeboat",
	"vest",
	"pirate",
	"regatta",
	"siren",
	"shipyard",
	"rowing",
	"wetsuit",
	"overboard",
	"salty",
	"swell",
	"fisherman",
	"clam",
	"tidal",
	"aquarium",
	"maritime",
	"mackerel",
	"boat",
	"raft",
	"coastguard",
	"paddleboard",
	"fishing",
	"shipmate",
	"shipshape",
	"seafaring",
	"harpoon",
	"float",
	"flotation",
	"seaplane",
	"fishing",
	"rigging",
	"porthole",
	"locker",
	"sunk",
	"seaworthy",
	"rowboat",
	"oceanography",
	"sailing",
	"yacht",
	"deck",
	"swimming",
	"swimming",
	"seadog",
	"shipwrecked",
	"oceanic",
	"coastline",
	"estuary",
	"island",
	"schooner",
	"bottom",
	"galleon",
	"mermaid",
	"cliff",
	"sea",
	"nautical",
	"stormy",
	"fishmonger",
	"harbour",
	"dolphinarium",
	"urchin",
	"octopus",
	"lobster",
	"crab",
	"waterfront",
	"spray",
	"boating",
	"yachting",
	"regatta",
	"rafting",
	"paddle",
	"beach",
	"sailor",
	"boatyard",
	"aqua",
	"outboard",
	"dock",
	"ferry",
	"blowhole",
	"starboard",
	"keelhaul",
	"seawall",
	"tiller",
	"gimbal",
	"maritime",
	"shoals",
	"drift",
	"jib",
	"topsail",
	"fog",
	"ocean",
	"sailcloth",
	"swim",
	"sailfish",
	"sandcastle",
	"kayak",
	"water",
	"trench",
	"hydrofoil",
	"zodiac",
	"yacht",
	"scuba",
	"boating",
	"hydrodynamics",
	"anchors",
	"mizzenmast",
	"bosun",
	"bulkhead",
	"binnacle",
	"shore",
	"overboard",
	"starfish",
	"seabird",
	"puffin",
	"tern",
	"gannet",
	"seal",
	"turtle",
	"jellyfish",
	"manatee",
	"otter",
	"orca",
	"dolphin",
	"whale",
	"kayaking",
	"diving",
	"snorkeling",
	"swimming",
	"surfboard",
	"bodyboarding",
	"parasailing",
	"waterpark",
	"nautical",
	"coastline",
	"stowaway",
	"sinking",
	"navy",
	"tugboat",
	"ocean",
	"tidal",
	"coastal",
	"sea",
	"aquatic",
	"starfish",
	"mermaid",
	"breeze",
	"oceanic",
	"shell",
	"shipwreck",
	"maritime",
	"diving",
	"surfing",
	"boat",
	"coral",
	"reef",
	"nautical",
	"underwater",
	"beach",
	"clam",
	"sea",
	"harbor",
	"tropical",
	"coastal",
	"port",
	"aquatic",
	"marine",
	"seafood",
	"marina",
	"docks",
	"whale",
	"whales",
	"dolphin",
	"fishing",
      ];
export{waterWords}
//вода
const animalWords = [
	"dog",
	"dogs",
	"cat",
	"cats",
	"elephant",
	"elephants",
	"lion",
	"lions",
	"tiger",
	"tigers",
	"giraffe",
	"giraffes",
	"monkey",
	"monkeys",
	"bear",
	"bears",
	"penguin",
	"penguins",
	"zebra",
	"zebras",
	"dolphin",
	"dolphins",
	"squirrel",
	"squirrels",
	"rabbit",
	"rabbits",
	"owl",
	"owls",
	"horse",
	"horses",
	"cow",
	"cows",
	"sheep",
	"sheep",
	"pig",
	"pigs",
	"chicken",
	"chickens",
	"duck",
	"ducks",
	"goat",
	"goats",
	"deer",
	"deer",
	"fox",
	"foxes",
	"wolf",
	"wolves",
	"rhinoceros",
	"rhinoceroses",
	"whale",
	"whales",
	"dolphin",
	"dolphins",
	"shark",
	"sharks",
	"octopus",
	"octopuses",
	"seal",
	"seals",
	"polar bear",
	"polar bears",
	"kangaroo",
	"kangaroos",
	"hippopotamus",
	"hippopotamuses",
	"crocodile",
	"crocodiles",
	"platypus",
	"platypuses",
	"koala",
	"koalas",
	"sloth",
	"sloths",
	"chameleon",
	"chameleons",
	"lizard",
	"lizards",
	"camel",
	"camels",
	"bat",
	"bats",
	"parrot",
	"parrots",
	"panda",
	"pandas",
	"jaguar",
	"jaguars",
	"hamster",
	"hamsters",
	"hedgehog",
	"hedgehogs",
	"crow",
	"crows",
	"eagle",
	"eagles",
	"falcon",
	"falcons",
	"gazelle",
	"gazelles",
	"jaguarundi",
	"jaguarundis",
	"mongoose",
	"mongooses",
	"otter",
	"otters",
	"puma",
	"pumas",
	"red panda",
	"red pandas",
	"turtle",
	"turtles",
	"walrus",
	"walruses",
	"whale shark",
	"whale sharks",
	"yak",
	"yaks",
	"blue jay",
	"blue jays",
	"crab",
	"crabs",
]
export{animalWords}
//список названий животных
const loveWords = [
	"affection",
	"adore", 
	"passion", 
	"intimacy", 
	"devotion", 
	"romance", 
	"admire", 
	"cherish", 
	"tenderness", 
	"commitment",
	"endearment", 
	"infatuation", 
	"adoration", 
	"relationship", 
	"cuddle", 
	"heartbeat", 
	"connect", 
	"sweetheart", 
	"eternal", 
	"togetherness",
	"hug", 
	"kiss", 
	"couple", 
	"soulmate", 
	"attraction", 
	"loyalty", 
	"desire", 
	"caring", 
	"warmth", 
	"partner", 
	"compassion",
	"unity", 
	"passionate", 
	"beloved", 
	"flirt", 
	"appreciation", 
	"friendship", 
	"emotion", 
	"heavenly", 
	"support",
	"smile", 
	"trust",
	"bond", 
	"heartfelt", 
	"romantic", 
	"adorable", 
	"sincerity", 
	"feelings", 
	"butterflies", 
	"tender", 
	"understanding", 
	"respect",
	"embrace",  
	"lovable", 
	"gaze", 
	"genuine", 
	"harmony", 
	"kisses", 
	"passionately", 
	"belonging", 
	"sympathy",
	"sentiment", 
	"swoon", 
	"yearning", 
	"connection", 
	"amour", 
	"devoted", 
	"passionflower", 
	"gentle", 
	"relationship", 
	"poetry",
	"touch", 
	"instinct", 
	"tantalize", 
	"soulful", 
	"intense", 
	"fondness", 
	"heartstrings", 
	"flame", 
	"perfection", 
	"glimmer", 
	"sight",
	"kindness", 
	"yearn", 
	"heartbeat", 
	"flutter", 
	"craving", 
	"tenderness", 
	"bonds", "courting", "caring", "ellipses", 
	"friendship", "loyalty", "cuddle", "gazing", "woo", "tangible", "sensuality", "passionate", "gaze", "adoring", "heartfelt",
	"gleam", "obliging", "kindhearted", "crush", "tasting", "warmth", "voracity", "sweetheart", "name", "amour", "pure",
	"intense", "passionate", "soulmate", "compassionate", "euphoria", "yearning", "longing", "rose", "beauty", "feel", "hold",
	"affectionate", "whisper", "giggle", "delight", "future", "trusting", "happiness", "kissing", "allure", "forever", "spark",
	"connection", "intertwine", "softness", "intimate", "gaze", "cherished", "wish", "yearn", "pleasure", "glimpse", "rainbow",
	"stars", "moon", "sky", "waves", "forever", "comfort", "date", "promise", "princess", "marvel", "heartfelt", "date",
	"cherish", "cute", "destined", "flame", "hero", "amazing", "comfort", "devoted", "sparkle", "sunshine", "poem",
	"song", "treasure", "dance", "eternity", "fairy", "god", "opportunity", "intense", "hugging", "special", "passionate",
	"kissable", "scent", "moonlight", "starlight", "compromise", "openness", "gentle", "breathtaking", "serenity", "soulful",
	"unity", "solace", "paradise", "desire", "quiet", "enchanted", "daydream", "flowers", "gentleness", "rapture", "melody",
	"magnetic", "grateful", "union", "whispering", "harmony", "trustworthy", "cherub", "wonder", "dreams", "affectionate",
	"companion", "butterflies", "mesmerize", "captivating", "secret", "bliss", "sigh", "passionflower", "glow", "honey",
	"smitten", "inspire", "charm", "soulful", "fascinate", "sincere", "romantic", "poetry", "kaleidoscope", "adoration",
	"innocence", "glisten", "forever", "heavenly", "truth", "promise", "perfection", "intertwined", "magnetic",
	"tenderhearted", "contentment", "forever", "vision", "heartfelt", "caring", "embrace", "entwine", "enchanted", "guitar",
	"darling", "breathtaking", "enthrall", "softness", "gentle embrace", "heartwarming", "twinkle", "mesmerizing",
	"radiant", "blissful", "inspirational", "lover", "ecstasy", "warmth", "cherub", "sunset", "blanket", "caress",
	"luminous", "protection", "purity", "relationship", "emotion", "fondness", "delicate", "irresistible", "candlelight",
	"infinite", "teardrop", "harmony", "gaze", "savor", "treat", "charming", "complete", "forevermore", "gaze", "shimmer",
	"apple of my eye", "season", "innocent", "darling", "swift", "heartbeat", "sunset", "impression", "adventure", "anniversary",
	"blending", "breakable", "brilliantly", "capture", "caring", "cruise", "delight", "beyond", "softly", "always", "powerful",
	"celebrate", "constant", "creation", "endless", "everyday", "everything", "everlasting", "forever", "magnify", "relationship",
	"intertwined", "journey", "kindness", "life", "light", "longing", "loyal", "romance", "soul", "special", "sweetness", "together", "treasure", "want", "wonderful", "amazing", "lovely",
    "heartwarming", "authentic", "radiant", "sparkling", "gentle", "harmonious", "purest", "enchantment", "whispers", "intertwine",
    "pulses", "connected", "vibrant", "blissful", "sensational", "cherished", "delicious", "caring", "passionate", "delighted",
    "endearing", "angelic", "twinkle", "tender", "solace", "adoring", "glimpse", "dreamy", "captivating", "magic", "shining",
    "serene", "fascinated", "admiration", "soothing", "bountiful", "glowing", "tantalizing", "gentleness", "enchanted", "radiance",
    "adorable", "rapture", "majestic", "kissable", "resonate", "flicker", "joyful", "beloved", "mesmerize", "charming", 
    "cherub", "emotionally", "endless", "carefree", "passionately", "intimate", "sparkle", "sensual", "whispering", "harmony",
    "eternal", "desire", "comforting", "bliss", "ceaseless", "soulful", "kisses", "intrigue", "affectionate", "tenderness",
    "lush", "loyalty", "affirmation", "harbor", "reverence", "intertwined", "exquisite", "flourish", "sharing", "exhilarate",
    "caress", "vivid", "cherish", "romantic", "sweetheart", "caress", "love", "longing",
    "affection",
    "adore",
    "passion",
    "intimacy",
    "devotion",
    "romance",
    "admire",
    "cherish",
    "tenderness",
    "commitment",
    "endearment",
    "infatuation",
    "adoration",
    "relationship",
    "cuddle",
    "hearbeat",
    "connect",
    "sweetheart",
    "eternal",
    "togetherness",
    "hug",
    "kiss",
    "couple",
    "soulmate",
    "attraction",
    "loyalty",
    "desire",
    "caring",
    "warmth",
    "partner",
    "compassion",
    "unity",
    "passionate",
    "beloved",
    "flirt",
    "appreciation",
    "friendship",
    "emotion",
    "heavenly",
    "support",
    "smile",
    "trust",
    "bond",
    "heartfelt",
    "romantic",
    "adorable",
    "sincerity",
    "feelings",
    "butterflies",
    "tender",
    "understanding",
    "respect",
    "embrace",
    "twin flame",
    "lovable",
    "gaze",
    "genuine",
    "harmony",
    "kisses",
    "passionately",
    "belonging",
    "sympathy",
    "sentiment",
    "swoon",
    "yearning",
    "connection",
    "amour",
    "devoted",
    "passionflower",
    "gentle",
    "relationship",
    "poetry",
    "touch",
    "instinct",
    "tantalize",
    "soulful",
    "intense",
    "fondness",
    "heartstrings",
    "flame",
    "perfection",
    "glimmer",
    "sight",
    "kindness",
    "yearn",
    "heartbeat",
    "flutter",
    "craving",
    "tenderness",
    "bonds",
    "courting",
    "caring",
    "ellipses",
    "relationship",
    "friendship",
    "loyalty",
    "cuddle",
    "gazing",
    "woo",
    "tangible",
    "sensuality",
    "passionate",
    "gaze",
    "adoring",
    "heartfelt",
    "gleam",
    "obliging",
    "kindhearted",
    "crush",
    "tasting",
    "warmth",
    "voracity",
    "sweetheart",
    "name",
    "amour",
    "pure",
    "intense"
]
export{loveWords}
//слова о чувствах и любви



const movieTitles = [
	"The Godfather",
	"Shawshank Redemption",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"Inglourious Basterds",
	"Whiplash",
	"Mad Max: Fury Road",
	"City of God",
	"The Grand Budapest Hotel",
	"The Terminator",
	"The Shawshank Redemption",
	"Eternal Sunshine of the Spotless Mind",
	"The Incredibles",
	"The Sixth Sense",
	"The Departed",
	"Se7en",
	"Inglourious Basterds",
	"The Princess Bride",
	"Rocky",
	"American Beauty",
	"The Truman Show",
	"The Social Network",
	"The Godfather Part II",
	"Saving Private Ryan",
	"The Dark Knight",
	"The Shining",
	"The Lion King",
	"Indiana Jones and the Last Crusade",
	"Jaws",
	"Scarface",
	"Alien",
	"The Big Lebowski",
	"The Departed",
	"Jurassic Park",
	"The Prestige",
	"There Will Be Blood",
	"The Shawshank Redemption",
	"The Dark Knight Rises",
	"Inception",
	"Django Unchained",
	"The Light Between Oceans",
	"The Avengers",
	"Forrest Gump",
	"The Green Mile",
	"The Godfather",
	"Fight Club",
	"The Matrix",
	"Schindler's List",
	"Dunkirk",
	"Whiplash",
	"The Godfather Part II",
	"The Lord of the Rings",
	"The Silence of the Lambs",
	"Star Wars",
	"The Usual Suspects",
	"The Dark Knight",
	"The Godfather",
	"Goodfellas",
	"Pulp Fiction",
	"The Green Mile",
	"Inception",
	"Schindler's List",
	"The Lord of the Rings",
	"Forrest Gump",
	"The Shawshank Redemption",
	"The Matrix",
	"The Dark Knight Rises",
	"The Grand Budapest Hotel",
	"Gladiator",
	"Braveheart",
	"The Departed",
	"Mad Max: Fury Road",
	"The Godfather Part II",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"The Godfather",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"Inglourious Basterds",
	"Whiplash",
	"Mad Max: Fury Road",
	"City of God",
	"The Grand Budapest Hotel",
	"The Terminator",
	"The Shawshank Redemption",
	"Eternal Sunshine of the Spotless Mind",
	"The Incredibles",
	"The Sixth Sense",
	"The Departed",
	"Se7en",
	"Inglourious Basterds",
	"The Princess Bride",
	"Rocky",
	"American Beauty",
	"The Truman Show",
	"The Social Network",
	"The Godfather Part II",
	"Saving Private Ryan",
	"The Dark Knight",
	"The Shining",
	"The Lion King",
	"Indiana Jones and the Last Crusade",
	"Jaws",
	"Scarface",
	"Alien",
	"The Big Lebowski",
	"The Departed",
	"Jurassic Park",
	"The Prestige",
	"There Will Be Blood",
	"The Shawshank Redemption",
	"The Dark Knight Rises",
	"Inception",
	"Django Unchained",
	"The Light Between Oceans",
	"The Avengers",
	"Forrest Gump",
	"The Green Mile",
	"The Godfather",
	"Fight Club",
	"The Matrix",
	"Schindler's List",
	"Dunkirk",
	"Whiplash",
	"The Godfather Part II",
	"The Lord of the Rings",
	"The Silence of the Lambs",
	"Star Wars",
	"The Usual Suspects",
	"The Dark Knight",
	"The Godfather",
	"Goodfellas",
	"Pulp Fiction",
	"The Green Mile",
	"Inception",
	"Schindler's List",
	"The Lord of the Rings",
	"Forrest Gump",
	"The Shawshank Redemption",
	"The Matrix",
	"The Dark Knight Rises",
	"The Grand Budapest Hotel",
	"Gladiator",
	"Braveheart",
	"The Departed",
	"Mad Max: Fury Road",
	"The Godfather Part II",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
	"The Godfather",
	"Pulp Fiction",
	"The Dark Knight",
	"Forrest Gump",
	"Titanic",
	"The Matrix",
	"Fight Club",
	"Inception",
	"Goodfellas",
	"The Silence of the Lambs",
	"Schindler's List",
	"The Lord of the Rings",
	"The Departed",
	"Gladiator",
	"Braveheart",
	"Jurassic Park",
	"The Shawshank Redemption",
	"The Green Mile",
	"The Lion King",
	"The Avengers",
	"Avatar",
	"Inglourious Basterds",
	"The Prestige",
	"The Revenant",
	"Django Unchained",
	"Interstellar",
	"The Godfather Part II",
	"The Dark Knight Rises",
	"The Social Network",
	"The Wolf of Wall Street",
]
export{movieTitles}
//список названий фильмов