

// Готовые короткие предложения и фразы
const beginnigMessages = [
	"It's you! Just the Smurf I want to see. What's smurfing you today?",
	"Oh, don't smurf me around, friendo!",
	"What's your name, little Smurf?",
	"What a lovely day, isn't it?",
	"How are you doing, friendly Smurf?",
	"Amazing that you're here!",
	"Hmm, are you supposed to be texting?",
	"What's it like to eat cheese?"
]
export {beginnigMessages};
//короткие вступительные фразы и small talk
const greetingsWords = [
	"hey",
	"hello",
	"hi",
	"q",
	"greetings",
	"day",
	"morning",
	"evening",
	"night",
	"howdy",
	"yo",
	"hiya",
]
export{greetingsWords}
const greetingsMessages = [
	"hello, little Smurf!",
	"oh hey there!",
	"good time, dear Smurf!",
	"greetings, my friend!",
	"hello and welcome! How are you doing today?",
	"oh hi-hi!",
	"hello to you, new Smurf!",
	"hey Smurf, how are you?",
	"ahh! Hello here",
]
export{greetingsMessages}
//короткие приветствия и пожелания
const negativeMessages =[
	"oh Smurf, don't be rude", 
	"go wash your mouth",
	"wash your tongue before speaking",
	"this is so rude to say",
	"don't you swear at me",
	"don't say swear words please",
	"I'm not gonna answer you until you stop swearing",
	"please, stop being rude",
	"you're getting on my nerves",
	"may God forgive you",
	"good Lord",
	"lord almighty",
	"ohh by God",
	"don't make me call my Smurfs"
]
export{negativeMessages}
const negativeWords =[
	"fuck",
	"fucking",
	"fucker",
	"fucks",
	"fucked",
	"motherfucker",
	"motherfuck",
	"motherfucking",
	"lox",
	"bitch",
	"bitches",
	"shit",
	"shitting",
	"shitted",
	"sht",
	"crap",
	"poop",
	"ass",
	"slut",
	"whore",
	"bullshit",
	"bullshitting",
	"bullshitted",
	"idiot",
	"asshole",
	"dick",
	"cunt",
	"pussy",
	"dumb",
	"dumber",
	"dumbest",
	"dumbass",
	"fool",
	"dull",
	"nyb",
	"noob",
	"damn",
	"freak",
	"freaking",
	"freaked",
	"damn",
	"douchebag",
	"gay",
	"fag",
	"faggot",
	"homo",
	"nigger",
	"niger",
	"niga",
	"nigga",
	"bastard",
	"jerk",
	"prick",
	"loser",
	"sucker",
	"nerd",
	"retard",
	"retarded",
	"dafaq",
	"hooker",
	"arse",
	"piss",
	"cock",
	"dickhead",
	"bollocks",
	"testicles",
	"bugger",
	"buggering",
	"buggers",
	"buggered",
	"git",
	"hell",
	"goddamn",
	"minger",
	"munter",
	"knob",
	"twat",
	"bellend",
	"snatch",
	"minge",
	"fucko",
	"fuckhead",
	"asshead",
	"hoe",
	"jade",
	"dork",
	"dorks",
	"dorky",
	"pansy",
	"scumbag",
	"wanker",
	"prat",
	"dwarf",
	"midget",
	"gnome",
	"crazy",

]
export{negativeWords}
//реакции на бранные слова и оскорбления
const noIdeaMessages = [
	"I'm not sure about your message",
	"...",
	"wait what?",
	"that's smurfing me a little",
	"I'm gonna be honest here: I've no idea about it",
	"I'm wanna be honest with you: I've no idea what you've jsut said",
	"that makes me think",
	"oh I don't know it",
	"sorry, it's not my field of activity",
	"wait, what? Could you please rephrase it for me?",
	"my little Smurf, you need to make yourself more clear",
	"excuse old Papa Smurf, what are you saying?",
	"I'm sorry, I cannot adress that",
	"I'm gonna pretend that you didn't say that",
	"Papa Smurf doesn't understand you",
	"I don't get it",
	"sorry, I'm kinda busy for this",
	"what a Smurf!",
	"I have no clue here",
	"use small words, I'm not as bright as you",
	"these words of yours... I don't know them",
	"I don't get it, my little Smurf",
	"am I getting old or it's just gibberish",
	"nonsense",
	"why did you type it?",
	"I don't understand you and it bothers me a lot",
	"say it again",
	"sometimes my brain betrays me. You say what?",
	"my mind is in a haze, sorry",
	"latter, little Smurf",
	"this is like a puzzle for me",
	"don't give me riddles like this",
	":)",
	":-)",
	"))",
	"lol",
	"xd",
	"amazing! What's that?",
	"come again please"

]
export {noIdeaMessages}
//короткие реакции на полное непонимание темы


// Готовые длинные предложения и фразы
const beingOldMessages = [
	"my little Smurf, I'm 542 years old",
	"old? I'm still as energetic as you",
	"being old is nothing to be ashamed of",
	"you called me old? It's so rude of you",
	"young Smurf, don't make a fool of you",
	"if you call me old I'm gonna disagree here",
	"in my time we didn't talk to our elders like that",
]
export{beingOldMessages}
const beingOldForms = [
	"old",
	"older",
	"oldest",
	"olds",
	"elder",
	"eldest",
	"ancient",
	"aged",
	"not young",
	"retired"
]
export{beingOldForms}
//реакции на слова о старости
const quotes = [
	"well, I should get going. I've got a Smurf village to rebuild",
	"I'm getting too old for this",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"knowledge is power, my little Smurf",
	"every journey begins with a single step, my little one",
	"there's no problem too big that we can't solve together, my Smurf",
	"never underestimate the power of teamwork, my little friend",
	"patience is a Smurf's best friend, remember that",
	"kindness is the language that the world speaks, my little Smurf",
	"there's always a solution if you look hard enough, my little one",
	"believe in yourself, my little Smurf, for you are capable of great things",
	"the power of positivity can move mountains, my little friend",
	"no Smurf is ever alone when we stand by each other, my little one",
	"the key to success is believing in yourself, my little Smurf",
	"never give up, my little one, for perseverance is the key to success",
	"the only limits are the ones we place on ourselves, my little friend",
	"trust in your instincts, my little Smurf, they will guide you well",
	"wisdom comes with experience, my little one, so make the most of every opportunity",
	"a little laughter goes a long way, my little Smurf",
	"forgiveness is a gift you give yourself, my little friend",
	"the truest wealth is found in the love of those around you",
	"respect is earned, not given, my little Smurf",
	"embrace your uniqueness, my little one, for it makes you special",
	"courage is not the absence of fear, my little Smurf, but the ability to face it head on",
	"life is too short to hold grudges, my little friend",
	"remember to always be kind to one another",
	"the power of love conquers all, my little Smurf",
	"dream big for anything is possible with determination",
	"the true test of character is how you treat others, my little friend",
	"success is not measured by material wealth, my little Smurf, but by the impact you make on others",
	"listen to your heart, it will never lead you astray",
	"change begins with you, my little Smurf, so be the change you wish to see in the world",
	"the greatest gift you can give someone is your time, my little friend",
	"life is full of challenges, my little one, but you are stronger than you think",
	"always strive to be your best, my little Smurf, for mediocrity is not in our vocabulary",
	"stay true to yourself, my little one, for you are already amazing just as you are",
	"happiness is a state of mind, my little friend, so choose to be happy today",
	"the power of positive thinking can transform your life, my little Smurf",
	"never lose hope, my little one, for tomorrow is a new day full of possibilities",
	"the world is a better place when we lift each other up",
	"life is too short to dwell on the past, so focus on the present and future",
	"gratitude opens the doors to abundance, my little one",
	"cherish every moment, my little Smurf, for time is our most precious gift",
	"a little kindness goes a long way, my little friend",
	"strength is not just physical, my little one, but also mental and emotional",
	"be the light in someone else's darkness, my little Smurf",
	"forgiveness is a gift you give yourself, my little friend",
	"life is a journey, my little one, so enjoy the ride and learn from every experience",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"never lose sight of your dreams, my little one, for they are the fuel that drives you forward",
	"the power of love can heal any wound, my little friend",
	"life is what you make it, my little Smurf, so make it magical",
	"courage is the ability to face your fears and do what needs to be done",
	"remember to always be grateful for the blessings in your life, my little Smurf",
	"the greatest gift you can give someone is your presence, my little friend",
	"the power of positivity can turn any situation around, my little one",
	"do not underestimate the power of a kind word, my little Smurf",
	"there's always a ray of light in the darkest of times, my little friend",
	"life is a journey, so enjoy the scenery along the way",
	"there is strength in vulnerability, my little Smurfs for it allows others to see your true self",
	"the only way to fail is to never try, my little friend",
	"believe in yourself, for you are capable of greatness",
	"the power of love can conquer any obstacle, my little Smurf",
	"never stop learning, my little friend, for knowledge is the key to unlocking your full potential",
	"every setback is a setup for a comeback",
	"patience is a virtue, my little Smurf, so practice it every day",
	"the best way to predict the future is to create it, my little friend",
	"your attitude determines your altitude, my little Smurf, so aim high",
	"kindness is the language of the heart, my little one",
	"life is too short to hold onto grudges, my little friend, so forgive and move on",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"the power of perseverance can move mountains, my little one",
	"dream big, my little Smurf, for the sky's the limit",
	"never give up on your dreams, my little friend, for they are the fuel that drives you forward",
	"the power of love can conquer any obstacle, my little one",
	"you are never alone, my little Smurf, for we are all in this together",
	"life is a journey, my little friend, so enjoy the ride and learn from every experience",
	"the power of positivity can transform your life",
	"change begins with you, my little Smurf, so be the change you wish to see in the world",
	"success is not just about material wealth, my little friend, but also about inner peace and happiness",
	"every day is a chance to start anew, my little one, so make the most of it",
	"life is too short to dwell on the past, my little Smurf, so focus on the present and future",
	"believe in yourself, my little friend, for you are capable of great things",
	"the power of love can heal any wound, my little one",
	"do not underestimate the power of kindness, my little Smurf",
	"courage is not the absence of fear, my little friend, but the ability to face it head on",
	"you are stronger than you think, my little one, so never give up",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"kindness is the key to a happy heart, my little friend",
	"life is a journey, so enjoy the ride and learn from every experience",
	"there is no problem too big that we can't solve together, my little Smurf",
	"the power of positivity can move mountains, my little friend",
	"always strive to be your best, my little one, for mediocrity is not in our vocabulary",
	"the greatest gift you can give someone is your time, my little Smurf",
	"life is full of challenges, my little friend, but you are stronger than you think",
	"dream big, for anything is possible with determination",
	"a little laughter goes a long way, my little Smurf",
	"patience is a Smurf's best friend, my little friend",
	"never underestimate the power of teamwork, my little one",
	"every journey begins with a single step, my little Smurf",
	"knowledge is power, my little friend",
	"the key to success is believing in yourself, my little one",
	"remember, my little Smurf, the truest wealth is found in the love of those around you",

]
export{quotes}
//длинные цитаты-наставления


// Слова для конструирования разборных предложений
const conjunction = [
	"and",
	"and ahh",
	"also",
	"but",
	"but amm",
	"actually",
	"so",
	"so ahh",
	"or",
	"or also",
	"and of course",
	"well",
	"for sure",
	"anyway",
	"in other words",
	"so please",
	"but please",
	"please",
	"you know what",
	"I'm telling you",
	" ",
]
export{conjunction}
// союзны и союзные слова
const agreeWords = [
	"yes",
	"yeah",
	"yeap",
	"ja",
	"naja",
	"yeh",
	"sure",
	"ok",
	"okay",
	"kk",
	"alright",
	"of course",
	"right",
	"oki",
	"fine",
	"no problem",
	"cool",
	"absolutely",
	"surely",
	"certainly",
	"good",
	"perfect",
	"nice",
	"amazing",
	"wonderful",
	"awesome",
	"great",
	"norm",
	"exactly",
	"precisely",
	"true",
	"fact",
	"facts",
	"correct",
	"agree",
]
export{agreeWords}
//слова согласия, как короткие, так и отдельные фразы
const disagreeWords = [
	"no",
	"not", //может быть проблемой для частоты
	"nope",
	"nuh",
	"nein",
	"bad",
	"sad",
	"nay",
	"disagree",
	"finally"
]
export{disagreeWords}
//слова несогласия, как короткие, так и отдельные фразы
const introductoryWords = [
	"accordingly",
	"additionally",
	"after all",
	"alas",
	"as a result",
	"be that as it may",
	"behold",
	"besides",
	"certainly",
	"consequently",
	"correspondingly",
	"despite this",
	"equally",
	"finally",
	"first of all",
	"for example",
	"furthermore",
	"hence",
	"hitherto",
	"however",
	"in addition",
	"in conclusion",
	"in fact",
	"in short",
	"in spite of",
	"indeed",
	"instead",
	"likewise",
	"meanwhile",
	"moreover",
	"namely",
	"nevertheless",
	"next",
	"nonetheless",
	"notwithstanding",
	"on the contrary",
	"on the one hand",
	"on the other hand",
	"otherwise",
	"similarly",
	"subsequently",
	"therefore",
	"thus",
	"to begin with",
	"to conclude",
	"to sum up",
	"truly",
	"undoubtedly",
	"verily",
	"yet",
]
export{introductoryWords}
//вводные вступительные, заключительные и нейтральные фразы
const binderPhrases = [
	"it is",
	"it's",
	"that is",
	"that's",
	"it is like",
	"it's like",
	"that is like",
	"that's like",
	"it sounds",
	"it looks",
	"it seems",
	"it seems like",
	"it is so",
	"it's so",
	"that is so",
	"that's so",
	"it is like so",
	"it's like so",
	"that is like so",
	"that's like so",
	"it sounds so",
	"it looks so",
	"it seems so",
	"it seems like so",
	"so it is",
	"so it's",
	"so that is",
	"so that's",
	"so it is like",
	"so it's like",
	"so that is like",
	"so that's like",
	"so it sounds",
	"so it looks",
	"so it seems",
	"so it seems like",
	"the thing is",
	"the deal is",
	"the situation is",
	"the words are"
]
export{binderPhrases}
//конструкции мосты, вроде "это есть" или "оно такое"
const descriptionWords = [
	"able",
	"agreeable",
	"amiable",
	"appealing",
	"astute",
	"authentic",
	"bighearted",
	"bright",
	"comfortable",
	"content",
	"cultured",
	"curious",
	"cute",
	"dashing",
	"defiant",
	"delightful",
	"discerning",
	"educated",
	"experienced",
	"fabulous",
	"fanciful",
	"farsighted",
	"fashionable",
	"friendly",
	"generous",
	"gentle",
	"gifted",
	"hopeful",
	"humble",
	"illustrious",
	"incisive",
	"intelligent",
	"joyful",
	"knowledgeable",
	"likable",
	"lucky",
	"mature",
	"popular",
	"professional",
	"punctual",
	"qualified",
	"resilient",
	"resourceful",
	"smart",
	"steady",
	"strong",
	"talented",
	"teachable",
	"unaffected",
	"well-respected",
	"absent-minded",
	"awful",
	"awkward",
	"bad-tempered",
	"bitter",
	"callous",
	"churlish",
	"closed-off",
	"clumsy",
	"cold",
	"combative",
	"contemptuous",
	"contentious",
	"crass",
	"crude",
	"dim",
	"fickle",
	"foolish",
	"grim",
	"grouchy",
	"gruff",
	"gullible",
	"haggard",
	"harried",
	"hateful",
	"hypercritical",
	"ignorant",
	"impudent",
	"insecure",
	"lazy",
	"meddlesome",
	"morose",
	"naughty",
	"nosy",
	"obnoxious",
	"petulant",
	"pompous",
	"quarrelsome",
	"querulous",
	"quick-tempered",
	"resentful",
	"short-tempered",
	"sneaky",
	"sour",
	"spiteful",
	"stupid",
	"sullen",
	"unlucky",
	"vulgar",
	"weak-willed",
	"amicable",
	"amusing",
	"anxious",
	"brave",
	"broad-minded",
	"carefree",
	"cheerful",
	"clever",
	"considerate",
	"consistent",
	"cowardly",
	"crazy",
	"creative",
	"cynical",
	"dedicated",
	"deep",
	"dependable",
	"determined",
	"diligent",
	"direct",
	"dispassionate",
	"earnest",
	"easygoing",
	"egotistical",
	"emotional",
	"empathetic",
	"exacting",
	"fair-minded",
	"faithful",
	"funny",
	"gentle",
	"giving",
	"hilarious",
	"honest",
	"humorous",
	"independent",
	"inflexible",
	"intellectual",
	"kind",
	"moody",
	"narrow-minded",
	"nervous",
	"nice",
	"open-minded",
	"overemotional",
	"passionate",
	"pessimistic",
	"powerful",
	"practical",
	"proud",
	"reliable",
	"self-centered",
	"self-confident",
	"sensible",
	"sensitive",
	"shrewd",
	"silly",
	"sincere",
	"sympathetic",
	"thoughtful",
	"thoughtless",
	"tough",
	"trustworthy",
	"unassuming",
	"understanding",
	"untrustworthy",
	"upbeat",
	"vain",
	"warmhearted",
	"wise",
	"adventurous",
	"affectionate",
	"aggressive",
	"aloof",
	"ambitious",
	"apologetic",
	"arrogant",
	"artistic",
	"assertive",
	"aware",
	"boastful",
	"bold",
	"boring",
	"bossy",
	"calm",
	"careful",
	"careless",
	"cautious",
	"charming",
	"chatty",
	"chivalrous",
	"civil",
	"clingy",
	"collaborative",
	"commanding",
	"communicative",
	"compassionate",
	"competitive",
	"compliant",
	"compromising",
	"confrontational",
	"conscientious",
	"cooperative",
	"courageous",
	"courteous",
	"cruel",
	"cynical",
	"deceitful",
	"decisive",
	"defensive",
	"deliberate",
	"devious",
	"dexterous",
	"diplomatic",
	"discreet",
	"dishonest",
	"domineering",
	"efficient",
	"eloquent",
	"energetic",
	"enterprising",
	"enthusiastic",
	"entrepreneurial",
	"envious",
	"extravagant",
	"extroverted",
	"fastidious",
	"fearless",
	"ferocious",
	"flamboyant",
	"flirtatious",
	"forceful",
	"friendly",
	"frugal",
	"gallant",
	"generous",
	"grumpy",
	"hardworking",
	"helpful",
	"hostile",
	"idle",
	"imaginative",
	"impartial",
	"impatient",
	"impolite",
	"impulsive",
	"inconsiderate",
	"indecisive",
	"indiscreet",
	"industrious",
	"intolerant",
	"introverted",
	"inventive",
	"irresponsible",
	"jealous",
	"laid-back",
	"lazy",
	"loud",
	"loving",
	"loyal",
	"mean",
	"modest",
	"nasty",
	"neat",
	"non-judgmental",
	"observant",
	"obstinate",
	"optimistic",
	"organized",
	"overcritical",
	"patient",
	"patronizing",
	"persistent",
	"polite",
	"possessive",
	"proactive",
	"quick-tempered",
	"quiet",
	"rational",
	"reserved",
	"resourceful",
	"responsive",
	"romantic",
	"rude",
	"secretive",
	"self-disciplined",
	"selfish",
	"shy",
	"sociable",
	"straightforward",
	"stubborn",
	"tactless",
	"talkative",
	"tidy",
	"unpredictable",
	"unreliable",
	"untidy",
	"vague",
	"wild",
	"witty",
	"adaptable",
	"affable",
	"analytical",
	"belligerent",
	"bigheaded",
	"calculating",
	"candid",
	"cantankerous",
	"capricious",
	"charismatic",
	"circumspect",
	"complex",
	"convivial",
	"cordial",
	"courtly",
	"crafty",
	"crotchety",
	"dauntless",
	"delicate",
	"dynamic",
	"ebullient",
	"eccentric",
	"erudite",
	"ethereal",
	"exuberant",
	"fervent",
	"finicky",
	"forthright",
	"frank",
	"freewheeling",
	"funky",
	"genial",
	"giddy",
	"glib",
	"gregarious",
	"kooky",
	"philosophical",
	"pigheaded",
	"pioneering",
	"placid",
	"plucky",
	"quick-witted" ,
	"reclusive",
	"shrewd",
	"tenacious",
	"touchy",
	"venal",
	"versatile",
	"visionary",
	"zealous",
]
export{descriptionWords}
//прилагательные и наречия для выражения своего мнения


// Работа с фотографиями
const pictureWords = [
	"picture",
	"pictures",
	"photo",
	"photos",
	"foto",
	"fotoes",
	"fotos",
	"photography",
	"photographies",
	"drawing",
	"drawings",
	"painting",
	"paintings",
	"image",
	"images",
	"photograph",
	"album",
	"albums",
	"shoot",
	"shoots",
	"snapshot",
	"snapshots",
	"illustration",
	"illustrations",
	"frame",
	"frames"
]
export{pictureWords};
const pictureMessages = [
	"Ohh, look at this photo!",
	"Yeah, I want to show you this picture of mine",
	"Look at this beautiful shot!",
	"I love this photo so much",
	"Have you seen this?",
	"Good days, check this one",
	"I didn't show you this?",
	"It's so cute!",
	"How I love our dearest Smurfs!",
	"Lovely picture, isn't it?",
	"I'm gonna show you this one",
	"OK, look at this",
	"You said a picture? Here you go",
	"No problem, look at this",
	"The photo quality may be old, but I love it",
	"This foto has a long history",
	"Here's my best picture of last year",
	"It was hard to capture but we got it!"
]
export{pictureMessages}
//короткие реакции на слова о фотографиях


const alex = [
	"alex",
	"lexa",
	"леха",
	"леша",
	"алешка",
	"алёшка",
	"origin",
	"lilkitchen",
	"parfe",
	"алексей",
	"alyosha"
]
export{alex}
const alexResponse = [
	"this name is",
	"oh Alex is",
	"I don't think that this so-called Alex is",
	"that name is",
	"you know, I find this name",
	"wait, Alex? He's",
	"I prefer to call him Alyosha because it's more",
	"don't call him like this, it's",
	"not sure about him, he is",
	"ohh, don't mention him, he's like Gargamel and it's",
	"him? I think he's friends with Gargamel",
	"this name, arrr, it's"
]
export{alexResponse}

const misha = [
	"misha",
	"mike",
	"michael",
	"theomorphic",
	"soters",
	"maxwell",
	"миша",
	"felixmk",
	"felix",
]
export{misha}

const questions = [
	"what",
	"where",
	"when",
	"why",
	"who",
	"which",
	"whose",
	"whom",
	"how",
]
export{questions}

const answers = [
	"yeah, what is it?",
	"what it's not?",
	"why not?",
	"why wouldn't it?",
	"whenever it happens",
	"how? I don't know, how are you, little Smurf?",
	"who isn't, right?",
	"who know, little one",
	"where is it leading to?",
	"where is the answer to this one? I don't know, little Smurf",
	"whose area of interest is this?",
	"for whom the bell tolls, little Smurf",
]
export{answers}