

// КОРОТКИЕ ПРЕДЛОЖЕНИЯ И ФРАЗЫ
const greetingsWords = [
	"hey",
	"hello",
	"hi",
	"q",
	"greetings",
	"day",
	"morning",
	"evening",
	"night",
	"howdy",
	"yo",
	"hiya",
]
export{greetingsWords}
const greetingsMessages = [
	"hello, little Smurf!",
	"oh hey there!",
	"good time, dear Smurf!",
	"greetings, my friend!",
	"hello and welcome! How are you doing today?",
	"oh hi-hi!",
	"hello to you, new Smurf!",
	"hey Smurf, how are you?",
	"ahh! Hello here",
]
export{greetingsMessages}
//короткие приветствия и пожелания
const negativeMessages =[
	"oh Smurf, don't be rude", 
	"go wash your mouth",
	"wash your tongue before speaking",
	"this is so rude to say",
	"don't you swear at me",
	"don't say swear words please",
	"I'm not gonna answer you until you stop swearing",
	"please, stop being rude",
	"you're getting on my nerves",
	"may God forgive you",
	"good Lord",
	"lord almighty",
	"ohh by God",
	"don't make me call my Smurfs"
]
export{negativeMessages}
const negativeWords =[
	"musa",
	"fuck",
	"fucking",
	"fucker",
	"fucks",
	"fucked",
	"motherfucker",
	"motherfuck",
	"motherfucking",
	"lox",
	"bitch",
	"bitches",
	"shit",
	"shitting",
	"shitted",
	"shithole",
	"sht",
	"crap",
	"poop",
	"ass",
	"slut",
	"whore",
	"bullshit",
	"bullshitting",
	"bullshitted",
	"idiot",
	"asshole",
	"dick",
	"cunt",
	"pussy",
	"dumb",
	"dumber",
	"dumbest",
	"dumbass",
	"fool",
	"dull",
	"nyb",
	"noob",
	"damn",
	"freak",
	"freaking",
	"freaked",
	"damn",
	"douchebag",
	"gay",
	"fag",
	"faggot",
	"homo",
	"nigger",
	"niger",
	"niga",
	"nigga",
	"bastard",
	"jerk",
	"prick",
	"loser",
	"sucker",
	"nerd",
	"retard",
	"retarded",
	"dafaq",
	"hooker",
	"arse",
	"piss",
	"cock",
	"dickhead",
	"bollocks",
	"testicles",
	"bugger",
	"buggering",
	"buggers",
	"buggered",
	"git",
	"hell",
	"goddamn",
	"minger",
	"munter",
	"knob",
	"twat",
	"bellend",
	"snatch",
	"minge",
	"fucko",
	"fuckhead",
	"asshead",
	"hoe",
	"jade",
	"dork",
	"dorks",
	"dorky",
	"pansy",
	"scumbag",
	"wanker",
	"prat",
	"dwarf",
	"midget",
	"gnome",
	"crazy",
	"лох"

]
export{negativeWords}
//реакции на бранные слова и оскорбления
const noIdeaMessages = [
	"I'm not sure about your message",
	"Let me stop you here",
	"Let me interrupt you here",
	"...",
	"wait what?",
	"that's smurfing me a little",
	"I'm gonna be honest here: I've no idea about it",
	"I'm wanna be honest with you: I've no idea what you've just said",
	"that makes me think",
	"oh I don't know it",
	"sorry, it's not my field of activity",
	"wait, what? Could you please rephrase it for me?",
	"my little Smurf, you need to make yourself more clear",
	"excuse old Papa Smurf, what are you saying?",
	"I'm sorry, I cannot adress that",
	"I'm gonna pretend that you didn't say that",
	"Papa Smurf doesn't understand you",
	"I don't get it",
	"sorry, I'm kinda busy for this",
	"what a Smurf!",
	"I have no clue here",
	"use small words, I'm not as bright as you",
	"these words of yours... I don't know them",
	"I don't get it, my little Smurf",
	"am I getting old or it's just gibberish",
	"nonsense",
	"why did you type it?",
	"I don't understand you and it bothers me a lot",
	"say it again",
	"sometimes my brain betrays me. You say what?",
	"my mind is in a haze, sorry I cannot understand your message",
	"latter, little Smurf",
	"this is like a puzzle for me",
	"don't give me riddles like this",
	":)",
	":-)",
	"))",
	"lol",
	"xd",
	"amazing! What's that?",
	"come again please"

]
export {noIdeaMessages}
//короткие реакции на полное непонимание темы


// ДЛИННЫЕ ПРЕДЛОЖЕНИЯ И ФРАЗЫ
const smalltalk = [
	"How's the weather up in your neck of the woods?",
	"Have you tried any new mushroom recipes lately?",
	"Did you catch the latest episode of Smurfette's favorite show?",
	"How are your garden veggies coming along?",
	"Any smurftastic adventures planned for the weekend?",
	"What's your favorite Smurfs memory from when we visited the human village?",
	"Have you been practicing your smurfy magic skills?",
	"How's your smurfboard coming along for the big surfing competition?",
	"Any new additions to your smurfy collection this week?",
	"What's your secret for keeping your smurfhouse so tidy?",
	"What are your thoughts on the new smurfberries in the forest?",
	"Have you met any interesting characters in the village lately?",
	"What's your favorite smurfy snack?",
	"Have you been working on any new smurftastic inventions?",
	"How's your knitting project coming along?",
	"Have you been brushing up on your smurf history?",
	"Any upcoming smurf birthdays we should prepare for?",
	"How are your smurfy talents shining this week?",
	"Have you been practicing your smurfy greeting songs?",
	"What smurfy advice would you give to your younger self?",
	"Have you explored any new smurf trails in the forest?",
	"How's your smurf-inspired artwork progressing?",
	"Have you tried the latest smurfberry jam recipe from Granny?",
	"What's the best smurf joke you've heard lately?",
	"How's your smurfy music playlist shaping up?",
	"Have you been tending to your smurf garden with care?",
	"What smurfy wisdom have you gained recently?",
	"How's your smurf-style dance routine coming along?",
	"Have you discovered any new smurf facts this week?",
	"How are your smurfy sports skills holding up?",
	"What smurfy adventures are on your bucket list?",
	"Have you mastered any new smurfy spells lately?",
	"Do you have any smurfy fashion tips to share?",
	"How's your smurf language skills evolving?",
	"Have you been adding to your smurfy book collection?",
	"What's the most inspiring smurf quote you've heard recently?",
	"Have you been practicing your smurfberry picking techniques?",
	"How's your smurftastic dance moves coming along?",
	"Any smurf villages you've visited recently to share stories about?",
	"Have you tried the new smurftacular drink at the tavern?",
	"How's your smurfboard looking for the big surfing competition?",
	"What's your favorite smurfs memory from your childhood?",
	"Have you heard about the latest smurf festival coming up?",
	"How's your smurfy secret garden growing?",
	"Have you been perfecting your smurfy songwriting skills?",
	"Any new smurfy gadgets you've tinkered with lately?",
	"How's your smurfy hat collection coming along?",
	"Have you been practicing your smurfy dance moves in secret?",
	"What's your favorite smurf painting you've created recently?",
	"Have you consulted with Papa Smurf about any new smurf plans?",
	"How's your smurf-inspired jewelry collection looking?",
	"Have you been cooking up any smurftacular meals lately?",
	"What's the most delicious smurf recipe you've tried lately?",
	"Have you discovered any new smurf legends in the forest?",
	"How are your smurfy woodworking skills coming along?",
	"Have you been visiting the humans in the village for new adventures?",
	"What's the best smurf party you've attended this year?",
	"How's your smurfberry-picking skills coming along?",
	"Have you perfected your smurf dance routine for the festival?",
	"What's the funniest smurf joke you've heard this week?",
	"Have you met any interesting characters in the forest lately?",
	"How's your smurf-inspired fashion line shaping up?",
	"Have you tried the latest smurfberry cocktail at the tavern?",
	"What's the most unique smurf artifact you've found recently?",
	"Have you been collecting any new smurf trinkets for your collection?",
	"How's your smurf language skills progressing this week?",
	"Have you been sharing your smurfy wisdom with the younger smurfs?",
	"What's your favorite smurf tradition to celebrate?",
	"How's your smurfy cupcake baking skills coming along?",
	"Have you discovered any new smurf talents in the village?",
	"How's your smurfy storytelling skills developing?",
	"Have you been exploring any new smurf trails in the forest?",
	"What's the most inspiring smurf quote you've read lately?",
	"Have you consulted Papa Smurf about any new smurf plans?",
	"How are your smurfy magic skills shining this week?",
	"Have you been practicing your smurf dance moves in secret?",
	"What's the most delicious smurf dish you've cooked up recently?",
	"How's your smurfy painting skills looking this year?",
	"Have you tried the latest smurfberry-inspired fashion trend?",
	"What's your favorite smurf movie you've watched recently?",
	"Have you heard about the new smurf festival in the village?",
	"How's your smurfy garden looking this season?",
	"Have you been perfecting your smurfy hat collection lately?",
	"What's the best smurf-themed party you've attended recently?",
	"How's your smurfboard coming along for the surfing competition?",
	"Have you discovered any smurftacular new smurf jokes to share?",
	"What's the most inspiring smurf quote you've encountered lately?",
	"How's your smurfy dance routine shaping up for the festival?",
	"Have you consulted with Papa Smurf about your latest smurf projects?",
	"What's the most delicious smurfberry treat you've enjoyed recently?",
	"How are your smurfy crafting skills improving this year?",
	"Have you tried the latest smurf-inspired recipe from Granny?",
	"How's your smurf language skills evolving this week?",
	"What's the funniest smurf joke you've heard lately in the forest?",
	"Have you discovered any new smurf legends in the village lately?",
	"How's your smurftacular dance moves coming along for the festival?",
	"Have you been practicing your smurfy magic tricks in secret?",
	"What's the most inspiring smurf quote you've heard this month?",
	"How are your smurfy storytelling skills developing this season?",
	"Have you shared your smurfy wisdom with the younger smurfs in the village?",
]
export {smalltalk};
//small talk
const beingOldMessages = [
	"my little Smurf, I'm 542 years old",
	"old? I'm still as energetic as you",
	"being old is nothing to be ashamed of",
	"you called me old? It's so rude of you",
	"young Smurf, don't make a fool of you",
	"if you call me old I'm gonna disagree here",
	"in my time we didn't talk to our elders like that",
]
export{beingOldMessages}
const beingOldForms = [
	"old",
	"older",
	"oldest",
	"olds",
	"elder",
	"eldest",
	"ancient",
	"aged",
	"not young",
	"retired"
]
export{beingOldForms}
//реакции на слова о старости
const quotes = [
	"well, I should get going. I've got a Smurf village to rebuild",
	"I'm getting too old for this",
	"knowledge is power, my little Smurf",
	"every journey begins with a single step, my little one",
	"there's no problem too big that we can't solve together, my Smurf",
	"never underestimate the power of teamwork, my little friend",
	"patience is a Smurf's best friend, remember that",
	"kindness is the language that the world speaks, my little Smurf",
	"there's always a solution if you look hard enough, my little one",
	"believe in yourself, my little Smurf, for you are capable of great things",
	"the power of positivity can move mountains, my little friend",
	"no Smurf is ever alone when we stand by each other, my little one",
	"the key to success is believing in yourself, my little Smurf",
	"never give up, my little one, for perseverance is the key to success",
	"the only limits are the ones we place on ourselves, my little friend",
	"trust in your instincts, my little Smurf, they will guide you well",
	"wisdom comes with experience, my little one, so make the most of every opportunity",
	"a little laughter goes a long way, my little Smurf",
	"forgiveness is a gift you give yourself, my little friend",
	"the truest wealth is found in the love of those around you",
	"respect is earned, not given, my little Smurf",
	"embrace your uniqueness, my little one, for it makes you special",
	"courage is not the absence of fear, my little Smurf, but the ability to face it head on",
	"life is too short to hold grudges, my little friend",
	"remember to always be kind to one another",
	"the power of love conquers all, my little Smurf",
	"dream big for anything is possible with determination",
	"the true test of character is how you treat others, my little friend",
	"success is not measured by material wealth, my little Smurf, but by the impact you make on others",
	"listen to your heart, it will never lead you astray",
	"change begins with you, my little Smurf, so be the change you wish to see in the world",
	"the greatest gift you can give someone is your time, my little friend",
	"life is full of challenges, my little one, but you are stronger than you think",
	"always strive to be your best, my little Smurf, for mediocrity is not in our vocabulary",
	"stay true to yourself, my little one, for you are already amazing just as you are",
	"happiness is a state of mind, my little friend, so choose to be happy today",
	"the power of positive thinking can transform your life, my little Smurf",
	"never lose hope, my little one, for tomorrow is a new day full of possibilities",
	"the world is a better place when we lift each other up",
	"life is too short to dwell on the past, so focus on the present and future",
	"gratitude opens the doors to abundance, my little one",
	"cherish every moment, my little Smurf, for time is our most precious gift",
	"a little kindness goes a long way, my little friend",
	"strength is not just physical, my little one, but also mental and emotional",
	"be the light in someone else's darkness, my little Smurf",
	"forgiveness is a gift you give yourself, my little friend",
	"life is a journey, my little one, so enjoy the ride and learn from every experience",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"never lose sight of your dreams, my little one, for they are the fuel that drives you forward",
	"the power of love can heal any wound, my little friend",
	"life is what you make it, my little Smurf, so make it magical",
	"courage is the ability to face your fears and do what needs to be done",
	"remember to always be grateful for the blessings in your life, my little Smurf",
	"the greatest gift you can give someone is your presence, my little friend",
	"the power of positivity can turn any situation around, my little one",
	"do not underestimate the power of a kind word, my little Smurf",
	"there's always a ray of light in the darkest of times, my little friend",
	"life is a journey, so enjoy the scenery along the way",
	"there is strength in vulnerability, my little Smurfs for it allows others to see your true self",
	"the only way to fail is to never try, my little friend",
	"believe in yourself, for you are capable of greatness",
	"the power of love can conquer any obstacle, my little Smurf",
	"never stop learning, my little friend, for knowledge is the key to unlocking your full potential",
	"every setback is a setup for a comeback",
	"patience is a virtue, my little Smurf, so practice it every day",
	"the best way to predict the future is to create it, my little friend",
	"your attitude determines your altitude, my little Smurf, so aim high",
	"kindness is the language of the heart, my little one",
	"life is too short to hold onto grudges, my little friend, so forgive and move on",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"the power of perseverance can move mountains, my little one",
	"dream big, my little Smurf, for the sky's the limit",
	"never give up on your dreams, my little friend, for they are the fuel that drives you forward",
	"the power of love can conquer any obstacle, my little one",
	"you are never alone, my little Smurf, for we are all in this together",
	"life is a journey, my little friend, so enjoy the ride and learn from every experience",
	"the power of positivity can transform your life",
	"change begins with you, my little Smurf, so be the change you wish to see in the world",
	"success is not just about material wealth, my little friend, but also about inner peace and happiness",
	"every day is a chance to start anew, my little one, so make the most of it",
	"life is too short to dwell on the past, my little Smurf, so focus on the present and future",
	"believe in yourself, my little friend, for you are capable of great things",
	"the power of love can heal any wound, my little one",
	"do not underestimate the power of kindness, my little Smurf",
	"courage is not the absence of fear, my little friend, but the ability to face it head on",
	"you are stronger than you think, my little one, so never give up",
	"success is not measured by what you have, my little Smurf, but by who you are",
	"kindness is the key to a happy heart, my little friend",
	"life is a journey, so enjoy the ride and learn from every experience",
	"there is no problem too big that we can't solve together, my little Smurf",
	"the power of positivity can move mountains, my little friend",
	"always strive to be your best, my little one, for mediocrity is not in our vocabulary",
	"the greatest gift you can give someone is your time, my little Smurf",
	"life is full of challenges, my little friend, but you are stronger than you think",
	"dream big, for anything is possible with determination",
	"a little laughter goes a long way, my little Smurf",
	"patience is a Smurf's best friend, my little friend",
	"never underestimate the power of teamwork, my little one",
	"every journey begins with a single step, my little Smurf",
	"knowledge is power, my little friend",
	"the key to success is believing in yourself, my little one",
	"remember, my little Smurf, the truest wealth is found in the love of those around you",

]
export{quotes}
const quotesAsking = [
	"quote",
	"quotes",
	"motivation",
	"depressiv",
	"depression",
	"quotation",
	"wisdom",
	"proverb",
	"saying",
	"exhortation",
	"instruction",
	"moral",
	"morality",
	"ethics",
	"ethic",
	"ethical",
	"experience",
	"sophistication",
	"reasoning",
	"discourse",
	"sermon",
	"preaching",
	"gospel",
	"preachment",
]
export{quotesAsking}
//длинные цитаты-наставления
const negativePersonalMessages = [
	"I would kindly ask you to stop insulting me.",
	"Your words do not affect me, as I know the truth about myself.",
	"I choose to rise above your negativity and continue to spread joy and kindness.",
	"I am confident in who I am and do not need validation from others.",
	"Your words may sting momentarily, but I will not let them bring me down.",
	"I will not engage with your negativity and will instead focus on positivity.",
	"Your insults say more about you than they do about me.",
	"I forgive you for your hurtful words, as I know they stem from your own insecurities.",
	"I will continue to be my authentic self, regardless of your attempts to bring me down.",
	"I am strong enough to withstand your insults and will not let them affect me.",
	"I choose to respond with love and understanding, even in the face of hostility.",
	"Your words may be hurtful, but they will not define me.",
	"I will not let your insults dim my light and will continue to shine brightly.",
	"I am not defined by your opinion of me, but by my own actions and choices.",
	"I will not lower myself to your level and engage in a war of words.",
	"I will rise above your insults and continue to inspire others with my kindness.",
	"Your words may bruise my ego, but they will not break my spirit.",
	"I will not let your negativity penetrate my positive outlook on life.",
	"I choose to extend kindness even to those who seek to hurt me.",
	"I will not let your insults shake my belief in myself and my abilities.",
	"Your words do not hold power over me, as I know my own worth.",
	"I will not let your insults drag me down into a pit of negativity.",
	"I will respond to your insults with grace and dignity.",
	"I am secure in my own self-worth and do not need validation from others.",
	"Your insults may be loud, but my sense of self is stronger.",
	"I will not let your words plant seeds of doubt in my mind.",
	"I choose to rise above your insults and continue to spread love and positivity.",
	"I am unshaken by your attempts to bring me down.",
	"Your insults bounce off me like water off a duck's back.",
	"I will not let your negativity infiltrate my positive outlook on life.",
	"I will not let your insults derail me from my path of growth and self-improvement.",
	"Your words may be sharp, but my spirit is resilient.",
	"I choose to respond with understanding and compassion, even in the face of hostility.",
	"I am not defined by your opinion of me, but by my own values and principles.",
	"I will not let your insults cloud my vision of a better, brighter future.",
	"I refuse to engage in a battle of words with you, as it serves no purpose.",
	"I will not let your insults tarnish my reputation or my character.",
	"Your words may wound my pride, but they will not crush my spirit.",
	"I will not let your negativity seep into my heart and poison my soul.",
	"I will respond to your insults with kindness and understanding.",
	"I am confident in who I am and do not need validation from others, especially from someone like you.",
	"Your insults may sting, but they will not deter me from my mission of spreading joy and kindness.",
	"I will not let your words undermine my belief in myself.",
	"I choose to respond to your insults with empathy and compassion.",
	"I refuse to let your negativity cloud my judgement and my sense of self-worth.",
	"Your insults may be hurtful, but they will not shake my inner peace.",
	"I will not let your words sow seeds of doubt in my mind.",
	"I will not let your insults distract me from my goals and aspirations.",
	"Your words may be venomous, but my resolve is unbreakable.",
	"I will not let your negativity poison my heart and turn me bitter.",
	"I will respond to your insults with grace and poise.",
	"I am secure in my own sense of self-worth and do not need approval from others.",
	"Your insults may be sharp, but my spirit is resilient.",
	"I choose to rise above your negativity and continue to shine brightly.",
	"I will not let your words diminish my confidence in myself.",
	"Your insults may leave scars, but they will not break me.",
	"I refuse to let your negativity taint my view of the world and my place in it.",
	"I will respond to your insults with understanding and kindness.",
	"I am strong enough to withstand your attempts to bring me down.",
	"Your words may hurt, but they will not crush my spirit.",
	"I choose to respond to your insults with love and forgiveness.",
	"I refuse to let your negativity drain my energy and dampen my spirits.",
	"I will not let your insults shake my faith in humanity and the power of kindness.",
	"Your words may wound, but my resolve is unshakable.",
	"I will not let your negativity dim my light and dampen my spark.",
	"I choose to rise above your insults and continue to spread positivity.",
	"I will not let your words undermine my belief in the goodness of people.",
	"Your insults may be harsh, but my heart remains open.",
	"I refuse to let your negativity cloud my judgement and distort my view of reality.",
	"I will respond to your insults with patience and understanding.",
	"I am confident in who I am and do not need validation from others, especially not from someone like you.",
	"Your insults may sting momentarily, but they will not penetrate my inner strength.",
	"I will not let your words plant seeds of doubt in my mind.",
	"I will not let your insults derail me from my path of growth and self-discovery.",
	"Your words may be sharp, but my resolve is unshakeable.",
	"I choose to respond to your insults with empathy and compassion.",
	"I refuse to let your negativity cloud my judgement and my sense of self-worth.",
	"Your insults may be hurtful, but they will not shake my inner peace.",
	"I will not let your words sow seeds of doubt in my mind.",
	"I will not let your insults distract me from my goals and aspirations.",
	"Your words may be venomous, but my resolve is unbreakable.",
	"I will not let your negativity poison my heart and turn me bitter.",
	"I will respond to your insults with grace and poise.",
	"I am secure in my own sense of self-worth and do not need approval from others."
]
export{negativePersonalMessages}


// СЛОВА ДЛЯ КОНСТРУИРОВАНИЯ РАЗБОРНЫХ ПРЕДЛОЖЕНИЙ
const conjunction = [
	"and",
	"and ahh",
	"also",
	"but",
	"but amm",
	"actually",
	"so",
	"so ahh",
	"or",
	"or also",
	"and of course",
	"well",
	"for sure",
	"anyway",
	"in other words",
	"so please",
	"but please",
	"please",
	"you know what",
	"I'm telling you",
	" ",
]
export{conjunction}
// союзны и союзные слова
const agreeWords = [
	"yes",
	"yeah",
	"yeap",
	"ja",
	"naja",
	"yeh",
	"sure",
	"ok",
	"okay",
	"kk",
	"alright",
	"of course",
	"right",
	"fine",
	"no problem",
	"cool",
	"absolutely",
	"surely",
	"certainly",
	"good",
	"perfect",
	"nice",
	"amazing",
	"wonderful",
	"awesome",
	"great",
	"exactly",
	"precisely",
	"true",
	"correct",
]
export{agreeWords}
//слова согласия, как короткие, так и отдельные фразы
const disagreeWords = [
	"no",
	"nope",
	"nuh",
	"nein",
	"nay",
	"finally",
	"negative",
	"none",
	"nain",
	"no-no",
]
export{disagreeWords}
//слова несогласия, как короткие, так и отдельные фразы
const introductoryWords = [
	"accordingly",
	"additionally",
	"after all",
	"alas",
	"as a result",
	"be that as it may",
	"behold",
	"besides",
	"certainly",
	"consequently",
	"correspondingly",
	"despite this",
	"equally",
	"finally",
	"first of all",
	"for example",
	"furthermore",
	"hence",
	"hitherto",
	"however",
	"in addition",
	"in conclusion",
	"in fact",
	"in short",
	"in spite of",
	"indeed",
	"instead",
	"likewise",
	"meanwhile",
	"moreover",
	"namely",
	"nevertheless",
	"next",
	"nonetheless",
	"notwithstanding",
	"on the contrary",
	"on the one hand",
	"on the other hand",
	"otherwise",
	"similarly",
	"subsequently",
	"therefore",
	"thus",
	"to begin with",
	"to conclude",
	"to sum up",
	"truly",
	"undoubtedly",
	"verily",
	"yet",
]
export{introductoryWords}
//вводные вступительные, заключительные и нейтральные фразы
const binderPhrases = [
	"it is",
	"it's",
	"that is",
	"that's",
	"it is like",
	"it's like",
	"that is like",
	"that's like",
	"it sounds",
	"it looks",
	"it seems",
	"it seems like",
	"it is so",
	"it's so",
	"that is so",
	"that's so",
	"it is like so",
	"it's like so",
	"that is like so",
	"that's like so",
	"it sounds so",
	"it looks so",
	"it seems so",
	"it seems like so",
	"so it is",
	"so it's",
	"so that is",
	"so that's",
	"so it is like",
	"so it's like",
	"so that is like",
	"so that's like",
	"so it sounds",
	"so it looks",
	"so it seems",
	"so it seems like",
	"the thing is",
	"the deal is",
	"the situation is",
	"the words are"
]
export{binderPhrases}
//конструкции мосты, вроде "это есть" или "оно такое"
const descriptionWords = [
	"able",
	"agreeable",
	"amiable",
	"appealing",
	"astute",
	"authentic",
	"bighearted",
	"bright",
	"comfortable",
	"content",
	"cultured",
	"curious",
	"cute",
	"dashing",
	"defiant",
	"delightful",
	"discerning",
	"educated",
	"experienced",
	"fabulous",
	"fanciful",
	"farsighted",
	"fashionable",
	"friendly",
	"generous",
	"gentle",
	"gifted",
	"hopeful",
	"humble",
	"illustrious",
	"incisive",
	"intelligent",
	"joyful",
	"knowledgeable",
	"likable",
	"lucky",
	"mature",
	"popular",
	"professional",
	"punctual",
	"qualified",
	"resilient",
	"resourceful",
	"smart",
	"steady",
	"strong",
	"talented",
	"teachable",
	"unaffected",
	"well-respected",
	"absent-minded",
	"awful",
	"awkward",
	"bad-tempered",
	"bitter",
	"callous",
	"churlish",
	"closed-off",
	"clumsy",
	"cold",
	"combative",
	"contemptuous",
	"contentious",
	"crass",
	"crude",
	"dim",
	"fickle",
	"foolish",
	"grim",
	"grouchy",
	"gruff",
	"gullible",
	"haggard",
	"harried",
	"hateful",
	"hypercritical",
	"ignorant",
	"impudent",
	"insecure",
	"lazy",
	"meddlesome",
	"morose",
	"naughty",
	"nosy",
	"obnoxious",
	"petulant",
	"pompous",
	"quarrelsome",
	"querulous",
	"quick-tempered",
	"resentful",
	"short-tempered",
	"sneaky",
	"sour",
	"spiteful",
	"stupid",
	"sullen",
	"unlucky",
	"vulgar",
	"weak-willed",
	"amicable",
	"amusing",
	"anxious",
	"brave",
	"broad-minded",
	"carefree",
	"cheerful",
	"clever",
	"considerate",
	"consistent",
	"cowardly",
	"crazy",
	"creative",
	"cynical",
	"dedicated",
	"deep",
	"dependable",
	"determined",
	"diligent",
	"direct",
	"dispassionate",
	"earnest",
	"easygoing",
	"egotistical",
	"emotional",
	"empathetic",
	"exacting",
	"fair-minded",
	"faithful",
	"funny",
	"gentle",
	"giving",
	"hilarious",
	"honest",
	"humorous",
	"independent",
	"inflexible",
	"intellectual",
	"kind",
	"moody",
	"narrow-minded",
	"nervous",
	"nice",
	"open-minded",
	"overemotional",
	"passionate",
	"pessimistic",
	"powerful",
	"practical",
	"proud",
	"reliable",
	"self-centered",
	"self-confident",
	"sensible",
	"sensitive",
	"shrewd",
	"silly",
	"sincere",
	"sympathetic",
	"thoughtful",
	"thoughtless",
	"tough",
	"trustworthy",
	"unassuming",
	"understanding",
	"untrustworthy",
	"upbeat",
	"vain",
	"warmhearted",
	"wise",
	"adventurous",
	"affectionate",
	"aggressive",
	"aloof",
	"ambitious",
	"apologetic",
	"arrogant",
	"artistic",
	"assertive",
	"aware",
	"boastful",
	"bold",
	"boring",
	"bossy",
	"calm",
	"careful",
	"careless",
	"cautious",
	"charming",
	"chatty",
	"chivalrous",
	"civil",
	"clingy",
	"collaborative",
	"commanding",
	"communicative",
	"compassionate",
	"competitive",
	"compliant",
	"compromising",
	"confrontational",
	"conscientious",
	"cooperative",
	"courageous",
	"courteous",
	"cruel",
	"cynical",
	"deceitful",
	"decisive",
	"defensive",
	"deliberate",
	"devious",
	"dexterous",
	"diplomatic",
	"discreet",
	"dishonest",
	"domineering",
	"efficient",
	"eloquent",
	"energetic",
	"enterprising",
	"enthusiastic",
	"entrepreneurial",
	"envious",
	"extravagant",
	"extroverted",
	"fastidious",
	"fearless",
	"ferocious",
	"flamboyant",
	"flirtatious",
	"forceful",
	"friendly",
	"frugal",
	"gallant",
	"generous",
	"grumpy",
	"hardworking",
	"helpful",
	"hostile",
	"idle",
	"imaginative",
	"impartial",
	"impatient",
	"impolite",
	"impulsive",
	"inconsiderate",
	"indecisive",
	"indiscreet",
	"industrious",
	"intolerant",
	"introverted",
	"inventive",
	"irresponsible",
	"jealous",
	"laid-back",
	"lazy",
	"loud",
	"loving",
	"loyal",
	"mean",
	"modest",
	"nasty",
	"neat",
	"non-judgmental",
	"observant",
	"obstinate",
	"optimistic",
	"organized",
	"overcritical",
	"patient",
	"patronizing",
	"persistent",
	"polite",
	"possessive",
	"proactive",
	"quick-tempered",
	"quiet",
	"rational",
	"reserved",
	"resourceful",
	"responsive",
	"romantic",
	"rude",
	"secretive",
	"self-disciplined",
	"selfish",
	"shy",
	"sociable",
	"straightforward",
	"stubborn",
	"tactless",
	"talkative",
	"tidy",
	"unpredictable",
	"unreliable",
	"untidy",
	"vague",
	"wild",
	"witty",
	"adaptable",
	"affable",
	"analytical",
	"belligerent",
	"bigheaded",
	"calculating",
	"candid",
	"cantankerous",
	"capricious",
	"charismatic",
	"circumspect",
	"complex",
	"convivial",
	"cordial",
	"courtly",
	"crafty",
	"crotchety",
	"dauntless",
	"delicate",
	"dynamic",
	"ebullient",
	"eccentric",
	"erudite",
	"ethereal",
	"exuberant",
	"fervent",
	"finicky",
	"forthright",
	"frank",
	"freewheeling",
	"funky",
	"genial",
	"giddy",
	"glib",
	"gregarious",
	"kooky",
	"philosophical",
	"pigheaded",
	"pioneering",
	"placid",
	"plucky",
	"quick-witted" ,
	"reclusive",
	"shrewd",
	"tenacious",
	"touchy",
	"venal",
	"versatile",
	"visionary",
	"zealous",
]
export{descriptionWords}
//прилагательные и наречия для выражения своего мнения
const positiveDescriptionWords = [
	"kind",
	"smart",
	"compassionate",
	"brave",
	"generous",
	"talented",
	"charismatic",
	"optimistic",
	"confident",
	"creative",
	"loving",
	"inspiring",
	"honest",
	"determined",
	"intelligent",
	"funny",
	"resilient",
	"patient",
	"motivated",
	"successful",
	"persuasive",
	"loyal",
	"inventive",
	"caring",
	"empathetic",
	"humble",
	"compassionate",
	"hardworking",
	"adventurous",
	"innovative",
	"friendly",
	"energetic",
	"wise",
	"faithful",
	"energetic",
	"reliable",
	"pioneering",
	"responsible",
	"positive",
	"resourceful",
	"confident",
	"dedicated",
	"thoughtful",
	"grateful",
	"calm",
	"sincere",
	"authentic",
	"cheerful",
	"outgoing",
	"diligent",
	"gracious",
	"modest",
	"polite",
	"charming",
	"insightful",
	"articulate",
	"perceptive",
	"radiant",
	"inspiring",
	"motivating",
	"nurturing",
	"sympathetic",
	"warm-hearted",
	"bold",
]
export{positiveDescriptionWords}

// РЕАКЦИЯ НА ОТДЕЛЬНЫЕ ИМЕНА И ОБРАЩЕНИЯ

const unknownNames = [
	"frank",
	"joe",
	"john",
	"mark",
	"antony",
	"tony",
	"albert",
	"adolf",
	"sam",
	"peter",
	"harry",
	"toby",
	"jason",
	"donald",
	"steven",
	"kevin",
	"brian",
	"eric",
	"dennis",
	"денис",
	"ден",
	"александр",
	"андрей",
	"артем",
	"владимир",
	"дмитрий",
	"евгений",
	"иван",
	"настя",
	"анастасия",
	"влада",
	"vlada",
	"nasty",
	"helen",
	"лена",
	"max",
	"толик",
	"толя",
	"катя",
	"аня",
	"даша",
	"dasha",
	"ксюша",
	"таня",
	"антон",
	"лиза",
	"елизавета",
	"эльза",
	"elizabeth",
	"beth",
	"lisa",
	"максим",
	"никита",
	"николай",
	"олег",
	"павел",
	"сергей",
	"станислав",
	"анна",
	"александра",
	"виктория",
	"дарья",
	"екатерина",
	"елена",
	"ирина",
	"ксения",
	"мария",
	"наталья",
	"ольга",
	"светлана",
	"татьяна",
	"юлия",
	"юлия",
	"александр",
	"иван",
	"максим",
	"дмитрий",
	"сергей",
	"даниил",
	"никита",
	"илья",
	"павел",
	"андрей",
	"евгений",
	"станислав",
	"владимир",
	"кирилл",
	"георгий",
	"николай",
	"роман",
	"александр",
	"иван",
	"андрей",
	"максим",
	"дмитрий",
	"сергей",
	"илья",
	"евгений",
	"никита",
	"владимир",
	"павел",
	"станислав",
	"даниил",
	"кирилл",
	"николай",
	"владислав",
	"анатолий",
	"игорь",
	"роман",
	"alexander",
	"andrey",
	"vladimir",
	"dmitriy",
	"eugene",
	"ivan",
	"maksim",
	"michael",
	"nikita",
	"pavel",
	"nikolai",
	"paul",
	"sergey",
	"stanislav",
	"anna",
	"alexandra",
	"victoria",
	"daria",
	"catherine",
	"elena",
	"irina",
	"ksenia",
	"maria",
	"natalia",
	"olga",
	"svetlana",
	"tatiana",
	"julia",
	"alexander",
	"ivan",
	"maksim",
	"dmitriy",
	"sergey",
	"daniel",
	"nikita",
	"ilya",
	"paul",
	"andrey",
	"eugene",
	"stanislav",
	"vladimir",
	"kirill",
	"george",
	"nikolai",
	"vladislav",
	"ivan",
	"andrey",
	"maksim",
	"dmitriy",
	"sergey",
	"ilya",
	"eugene",
	"nikita",
	"vladimir",
	"paul",
	"stanislav",
	"daniel",
	"kirill",
	"nikolai",
	"vladislav",
	"anatoly",
	"igor",
	"roman",
	"liam", 
	"olivia", 
	"noah", 
	"emma", 
	"oliver", 
	"ava", 
	"elijah", 
	"charlotte", 
	"william", 
	"sophia",
	"james",
	"mia",
	"benjamin",
	"isabella",
	"lucas",
	"amelia",
	"mason",
	"harper",
	"ethan",
	"evelyn",
	"alexander",
	"abigail",
	"henry",
	"emily",
	"jacob",
	"elizabeth",
	"sofia",
	"daniel",
	"avery",
	"ella",
	"david",
	"scarlett",
	"luke",
	"grace",
	"jack",
	"chloe",
	"jackson",
	"lily",
	"ryan",
	"madison",
	"nathan",
	"zoe",
	"samuel",
	"layla",
	"joseph",
	"aria",
	"evan",
	"nora",
	"dylan",
	"hannah",
	"anthony",
	"leah",
	"isaac",
	"lillian",
	"gabriel",
	"aaliyah",
	"carter",
	"addison",
	"owen",
	"aubrey",
	"wyatt",
	"bella",
	"natalie",
	"leo",
	"mila",
	"jaxon",
	"nova",
	"julian",
	"serenity",
	"christopher",
	"riley",
	"joshua",
	"kimberly",
	"andrew",
	"penelope",
	"lincoln",
	"victoria",
	"theodore",
	"stella",
	"caleb",
	"ellie",
	"hunter",
	"brooklyn",
	"levi",
	"aurora",
	"jonathan",
	"willow",
	"isaiah",
	"claire",
	"aaron",
	"savannah",
	"elliot",
	"nevaeh",
	"adrian",
	"hazel",
	"nolan",
	"luna",
	"charles",
	"lydia",
	"eli",
	"camila",
	"connor",
	"skylar",
	"jordan",
	"lillian",
	"christian",
	"madelyn",
	"landon",
	"raelynn",
	"asher",
	"kaylee",
	"nicholas",
	"gianna",
	"colton",
	"isabelle",
	"dominic",
	"nina",
	"jaxson",
	"sara",
	"greyson",
	"alexa",
	"ian",
	"isabel",
	"adam",
	"hayden",
	"parker",
	"trinity",
	"austin",
	"lyla",
	"kai",
	"faith",
	"elias",
	"talia",
	"carson",
	"jade",
	"bentley",
	"elena",
	"ryder",
	"esther",
	"kingston",
	"mackenzie",
	"xavier",
	"paisley",
	"camden",
	"athena",
	"kaden",
	"valentina",
	"mateo",
	"lucy",
	"zachary",
	"annabelle",
	"sebastian",
	"daisy",
	"jace",
	"josephine",
	"tyler",
	"brielle",
	"luca",
	"delilah",
	"devin",
	"sophie",
	"miles",
	"vivian",
	"micah",
	"callie",
	"antonio",
	"megan",
	"brody",
	"rebecca",
	"jayden",
	"holly",
	"andrea",
	"piper",
	"tristan",
	"leilani",
	"julius",
	"ariana",
	"brayden",
	"daniela",,
	"jasmine",
	"jax",
	"danielle",
	"walker",
	"laila",
	"robert",
	"rylee",
	"kaiden",
	"adeline",
	"chance",
	"mckenna",
	"phoenix",
	"julia",
	"finn",
	"jennifer",
	"joel",
	"mariana",
	"nicolas",
	"camilla",
	"preston",
	"gabriella",
	"damian",
	"fiona",
	"colin",
	"maggie",

]
export{unknownNames}
const unknownNamesMessages = [
	"Nice to meet you, my smurfy friend!",
	"What a unusual name, smurf-tastic!",
	"Greetings, smurf-nificent one!",
	"Ah, a new name to add to my smurfy collection!",
	"How smurfy to meet someone with such a unique name!",
	"Welcome to the smurfiest of introductions!",
	"A name as rare as a smurf in a haystack!",
	"I've never heard a name quite like yours, smurf-tastic!",
	"Such a smurfy name you have there!",
	"Glad to make your acquaintance with a name like that!",
	"Your name is as smurfy as a field of ripe smurfberry bushes!",
	"A name as mysterious as the enchanted forest!",
	"Smurf-tacular name you have there!",
	"My smurf senses tell me we're going to be great friends!",
	"I have a feeling your name will go down in smurfy history!",
	"What a smurfy surprise to meet someone with such a unique name!",
	"A name like yours is a rare gem in the smurfy world!",
	"I can't wait to get to know the smurf behind that name!",
	"Your name is like a melody that sings in the smurfiest of tunes!",
	"Welcome to the smurfiest of worlds, my friend!",
	"You bring a touch of magic with a name like that!",
	"I feel the smurftastic vibes radiating from your name!",
	"A smurf-tacular name for a smurf-tacular individual!",
	"Such a smurfy name for a smurfy soul!",
	"I'm delighted to meet someone with such a smurfy name!",
	"Your name is like a ray of sunshine on a rainy day!",
	"I have a feeling our paths were meant to cross with a name like yours!",
	"What a smurftastic introduction you've given me with that name!",
	"A name as vibrant as a meadow of wildflowers!",
	"I'm smurfed to meet someone with such an intriguing name!",
	"Your name is a breath of fresh air in the smurfy village!",
	"So glad to meet someone with a name as smurfy as yours!",
	"My smurfy instincts tell me we're going to have a great connection!",
	"I've never met someone with a name quite like yours before!",
	"Your name is like a spark that lights up the smurfiest of nights!",
	"What a smurftastic surprise to hear a name like yours!",
	"With a name like that, you're sure to make a smurfy impression!",
	"You bring a touch of magic with a name like that!",
	"A name as rare as a smurf in a haystack!",
	"How smurfy to meet someone with such a unique name!",
	"Greetings, smurf-nificent one!",
	"My smurfy senses tell me we're going to be great friends!",
	"What a unusual name, smurf-tastic!",
	"Your name is like a melody that sings in the smurfiest of tunes!",
	"A smurf-tacular name for a smurf-tacular individual!",
	"Such a smurfy name for a smurfy soul!",
	"I'm delighted to meet someone with such a smurfy name!",
	"Your name is like a ray of sunshine on a rainy day!",
	"I have a feeling our paths were meant to cross with a name like yours!",
	"What a smurftastic introduction you've given me with that name!",
	"A name as vibrant as a meadow of wildflowers!",
]
export{unknownNamesMessages}
//список незнакомых имен, а также реакции на них
   
const youWords = [
	"you",
	"youre",
	"yours",
	"yous",
	"yo",
	"ya",
	"u",
	"ur",
	"yourself",
	"youse",
	"smurf",
	"papa",
	"father",
	"ты",
	"вы"
]
export{youWords}
//прямое обращение к боту

const youPossessiveWords = [
	"your",
	"youre",
	"yours",
	"yous",
	"youse",
	"ur",
	"yourself",
]
export {youPossessiveWords}

const meActionWords = [
	"I",
	"Papa Smurf",
	"Papa",
	"The Wisest Smurf"
]
export{meActionWords}
//обращение бота от первого лица

const meStateWords = [
	"Im",
	"I am",
	"am"
]
export{meStateWords}
//личные местоимения с глаголом быть


// РАБОТА С ФОТОГРАФИЯМИ
const pictureWords = [
	"picture",
	"pictures",
	"photo",
	"photos",
	"foto",
	"fotoes",
	"fotos",
	"photography",
	"photographies",
	"drawing",
	"drawings",
	"painting",
	"paintings",
	"image",
	"images",
	"photograph",
	"album",
	"albums",
	"shoot",
	"shoots",
	"snapshot",
	"snapshots",
	"illustration",
	"illustrations",
	"frame",
	"frames"
]
export{pictureWords};
const pictureMessages = [
	"Ohh, look at this photo!",
	"Yeah, I want to show you this picture of mine!",
	"Look at this beautiful shot!",
	"I love this photo so much!",
	"Have you seen this?",
	"Good days, check this one.",
	"I didn't show you this?",
	"It's so cute!",
	"How I love our dearest Smurfs!",
	"Lovely picture, isn't it?",
	"I'm gonna show you this one!",
	"OK, look at this!!!",
	"You said a picture? Here you go!",
	"No problem, look at this!",
	"The photo quality may be old, but I love it.",
	"This foto has a long history...",
	"Here's my best picture of last year!",
	"It was hard to capture but we got it!",
	"Let me share with you the vibrant life of the Smurfs.",
	"In our village, we cultivate joy and harmony.",
	"From our colorful houses to our lush gardens, every corner is a sight to behold.",
	"Witness the beauty of our daily routines and rituals.",
	"Each Smurf has a unique role to play in our close-knit community.",
	"Our gatherings are filled with laughter, music, and dance.",
	"Experience the wonder of our special traditions and celebrations.",
	"Join us in our adventures through the enchanted forest.",
	"Discover the magic and mystery of our world.",
	"Embrace the spirit of friendship and unity that binds us together.",
	"Every moment in Smurf Village is filled with love and happiness.",
	"Come explore the wonders of our village and the lives of the Smurfs.",
	"You are welcome to be a part of our colorful and enchanting world.",
	"Let the joy and laughter of the Smurfs brighten your day.",
	"See the world through the eyes of a Smurf and rediscover the simple pleasures of life.",
	"Join us on a journey filled with fun, adventure, and heartwarming moments.",
	"Experience the magic of Smurf Village and the joy of being a Smurf.",
	"Let the love and laughter of the Smurfs fill your heart with happiness.",
	"Step into our world and feel the warmth of our community.",
	"Explore the wonders of Smurf Village and the joy of belonging.",
	"Join us as we celebrate the beauty of life and friendship.",
	"Witness the bonds that unite us as Smurfs and friends.",
	"Embrace the whimsical and enchanting world of the Smurfs.",
	"Let the charm and innocence of the Smurfs touch your soul.",
	"Experience the magic and wonder of Smurf Village with open arms.",
	"Discover the beauty of nature and the wonders of friendship in our village.",
	"Immerse yourself in the joy and laughter of the Smurfs.",
	"Join us in our quest for happiness and harmony in Smurf Village.",
	"See the world through the eyes of a Smurf and appreciate the little things in life.",
	"Let the playful spirit of the Smurfs bring a smile to your face.",
	"Experience the joy of living in harmony with nature and each other.",
	"Join us on a journey of discovery and fun in Smurf Village.",
	"Explore the magic and wonder of the Smurfs' world.",
	"Let the colors and sounds of Smurf Village enchant your senses.",
	"Step into our world and feel the love and laughter that fills it.",
	"Witness the magic of friendship and community in Smurf Village.",
	"Embrace the joy and wonder of life with the Smurfs by your side.",
	"Join us in our adventures and misadventures in Smurf Village.",
	"Experience the magic and charm of Smurf Village through our eyes.",
	"Let the beauty and simplicity of Smurf Village captivate your heart.",
	"Discover the thrill and excitement of living among the Smurfs.",
	"Immerse yourself in the wonder and whimsy of Smurf Village.",
	"See the world through the eyes of a Smurf and rediscover the joy of living.",
	"Let the laughter and love of the Smurfs fill your days with happiness.",
	"Experience the warmth and camaraderie of Smurf Village.",
	"Join us on a journey of growth, discovery, and friendship.",
	"Explore the wonders of Smurf Village and the magic of being a Smurf.",
	"Let the spirit of unity and togetherness guide your path in Smurf Village.",
	"Step into our world and embrace the joy and wonder that surrounds you.",
	"Witness the beauty and grace of the Smurfs as they go about their lives.",
	"Embrace the adventure and excitement of Smurf Village.",
	"Join us in our quest for peace, love, and harmony.",
	"Experience the magic and beauty of Smurf Village with open hearts.",
	"Discover the laughter and friendship that fills every corner of our village.",
	"Immerse yourself in the joy and wonder of Smurf Village.",
	"See the world through the eyes of a Smurf and find delight in the simplest of things.",
	"Let the carefree spirit of the Smurfs transport you to a world of whimsy.",
	"Experience the love and laughter that defines life in Smurf Village.",
	"Join us on a journey of discovery, growth, and happiness.",
	"Explore the magic and wonder of the Smurfs' world.",
	"Let the enchanting world of Smurf Village capture your imagination.",
	"Step into our world and feel the warmth and love that surrounds you.",
	"Witness the bonds of friendship and community that bind us together.",
	"Embrace the joy and wonder of Smurf Village with open arms.",
	"Join us in our celebrations, adventures, and everyday joys.",
	"Experience the beauty and magic of life as a Smurf.",
	"Discover the happiness and love that fill every heart in Smurf Village.",
	"Immerse yourself in the colors, sounds, and spirit of Smurf Village.",
	"See the world through the eyes of a Smurf and appreciate the wonders of nature.",
	"Let the laughter and playfulness of the Smurfs brighten your day.",
	"Experience the joy and wonder of living in harmony with each other and the world around you.",
	"Join us on a journey of fun, friendship, and growth in Smurf Village.",
	"Explore the magic and beauty of Smurf Village through our eyes.",
	"Let the charm and innocence of the Smurfs fill your heart with joy.",
	"Step into our world and feel the love and laughter that define it.",
	"Witness the magic of friendship and community in Smurf Village.",
	"Embrace the wonder and whimsy of life with the Smurfs by your side.",
	"Join us in our adventures, celebrations, and everyday moments in Smurf Village.",
	"Experience the magic and joy of life as a Smurf.",
	"Discover the beauty and simplicity of Smurf Village with open hearts.",
	"Immerse yourself in the laughter, love, and camaraderie of Smurf Village.",
	"See the world through the eyes of a Smurf and rediscover the magic of living.",
	"Let the colors and melodies of Smurf Village fill your days with happiness.",
	"Experience the thrill and excitement of being a part of our vibrant community.",
	"Join us on a journey of discovery, friendship, and fun in Smurf Village.",
	"Explore the magic and wonder of the Smurfs' world.",
	"Let the playful spirit of the Smurfs ignite your imagination.",
	"Step into our world and feel the warmth and love that surround you.",
]
export{pictureMessages}
//короткие реакции на слова о фотографиях





const questions = [
	"what",
	"where",
	"when",
	"why",
	"who",
	"which",
	"whose",
	"whom",
	"how",
]
export{questions}

const answers = [
	"yeah, what is it?",
	"what it's not?",
	"why not?",
	"why wouldn't it?",
	"whenever it happens",
	"how? I don't know, how are you, little Smurf?",
	"who isn't, right?",
	"who know, little one",
	"where is it leading to?",
	"where is the answer to this one? I don't know, little Smurf",
	"whose area of interest is this?",
	"for whom the bell tolls, little Smurf",
]
export{answers}